In [1]:
import BERTModel
import data_load_for_Transformer as dlft
import Utility
import os
import torch
import imp
imp.reload(BERTModel)

<module 'BERTModel' from 'e:\\ML\\chatbot\\BERTChatBot_with_pretrained_model\\BERTModel.py'>

In [2]:
# print("Initiating the hyperparameters...")
# num_hiddens, num_layers, dropout, batch_size, num_steps = 32, 2, 0.1, 128, 16
# lr, num_epochs, device = 0.001, 200, Utility.try_gpu()
# ffn_num_input, ffn_num_hiddens, num_heads = 32, 64, 4
# key_size, query_size, value_size = 32, 32, 32
# norm_shape = [32]

In [2]:
print("Initiating the hyperparameters...")
num_hiddens, num_layers, dropout, batch_size, num_steps = 128, 2, 0.1, 384, 16
lr, num_epochs, device = 0.0001, 20, Utility.try_gpu()
ffn_num_input, ffn_num_hiddens, num_heads = 128, 128, 8
key_size, query_size, value_size = 128, 128, 128
norm_shape = [128]
using_bias = True

Initiating the hyperparameters...


In [4]:
print("Building the vocabulary...")
train_iter, vocab = dlft.load_data_xhj_for_Transformer(batch_size, num_steps,load=True)
len(train_iter), len(vocab)

Building the vocabulary...
['[PAD]', '[UNK]', '[CLS]', '[SEP]', '[MASK]', '你', '我', '的', '了', '是']


(1034, 2)

In [5]:
print("Rebuilding the Model...")
encoder = BERTModel.TransformerEncoder(
    len(vocab), key_size, query_size, value_size, num_hiddens,
    norm_shape, ffn_num_input, ffn_num_hiddens, num_heads,
    num_layers, dropout, using_bias)
decoder = BERTModel.TransformerDecoder(
    len(vocab), key_size, query_size, value_size, num_hiddens,
    norm_shape, ffn_num_input, ffn_num_hiddens, num_heads,
    num_layers, dropout)
net = BERTModel.EncoderDecoder(encoder, decoder)
try:
    checkpoint_prefix = os.path.join("model_data/model_transformer.pt")
    checkpoint = torch.load(checkpoint_prefix)
    net.load_state_dict(checkpoint['model_state_dict'])
except Exception as e:
    print("Can not load the model with error:", e)

print("Ready to working...")
def predict(src_sentence):
    return BERTModel.predict_seq2seq(net, src_sentence, vocab, vocab, num_steps,
                    device, save_attention_weights=False)

Rebuilding the Model...
Can not load the model with error: [Errno 2] No such file or directory: 'model_data/model_transformer.pt'
Ready to working...


In [6]:
print(vocab.to_tokens([0,1,2,3,4,5,6,7,8,9]))

['<unk>', '<pad>', 'mask2', '<bos>', '<eos>', '你', '我', '的', '了', '是']


In [7]:
BERTModel.train_seq2seq(net, train_iter, lr, num_epochs, batch_size, vocab, device)

KeyboardInterrupt: 

In [ ]:
BERTModel.train_seq2seq(net, train_iter, lr, num_epochs, batch_size, vocab, device)

In [ ]:
predict("你好")

In [3]:
predict("今天天气不错")

src ['今', '天', '天', '气', '不', '错']
src_tokens= [7286, 627, 627, 1282, 11, 163, 3]
tp_src_tokens [7286, 627, 627, 1282, 11, 163, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1]
enc_outputs tensor([[[-4.7648e-02,  2.1777e-01,  6.3488e-02,  2.8417e-02, -9.2419e-02,
          -2.5271e-02,  1.0760e-01,  1.6060e-01,  3.0683e-02,  5.1947e-02,
          -7.5754e-02, -2.2376e-02, -1.3619e-01,  6.1030e-02,  1.0808e-01,
           2.0210e-02, -2.1162e-02,  2.7419e-04,  1.8149e-01, -2.0128e-03,
          -7.8765e-02, -1.1256e-01, -3.5420e-03, -1.0250e-02,  1.3250e-01,
           2.4457e-02,  7.9618e-02,  1.4568e-01, -2.8701e-02, -1.0381e-01,
          -8.9158e-02, -1.2742e-02],
         [ 3.0389e-03,  2.0170e-01,  4.4093e-02,  2.4734e-02, -5.9368e-02,
          -7.8783e-02,  1.2622e-01,  1.2904e-01,  4.0874e-02,  5.1486e-02,
          -7.6375e-02, -2.7593e-02, -1.6642e-01,  5.8921e-02,  1.3456e-01,
           2.8648e-02, -2.9015e-02, -3.2208e-02,  8.6804e-02,  4.3393e-02,
          -6.8488e-02, -1.1664e-01,  7.5889

'='

In [4]:
predict("你叫什么名字")

src ['你', '叫', '什', '么', '名', '字']
src_tokens= [4, 65, 4423, 21, 2622, 964, 3]
tp_src_tokens [4, 65, 4423, 21, 2622, 964, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1]
enc_outputs tensor([[[ 0.1969,  0.1436, -0.0772,  0.0018, -0.0761, -0.0181,  0.1787,
          -0.0380,  0.0319,  0.0525, -0.0316, -0.0139, -0.0655,  0.0068,
           0.1188,  0.0563, -0.0451, -0.0943, -0.3334,  0.1194, -0.0459,
           0.0010, -0.0121, -0.0086, -0.0243,  0.0828,  0.2981,  0.1206,
          -0.0396, -0.0989, -0.0042, -0.0949],
         [ 0.1498,  0.0338, -0.0677, -0.0004, -0.1021,  0.0237,  0.1708,
          -0.0302,  0.0287,  0.0527, -0.0496, -0.0226, -0.0528,  0.0102,
           0.1071,  0.0491, -0.0330, -0.0859, -0.2743,  0.0435, -0.0233,
           0.0030,  0.0099, -0.0177,  0.0058,  0.0756,  0.2667,  0.1455,
          -0.0350, -0.0856, -0.0374, -0.0927],
         [ 0.1842,  0.1141, -0.0724,  0.0030, -0.0875, -0.0235,  0.1857,
          -0.0254,  0.0351,  0.0523, -0.0399, -0.0177, -0.0716,  0.0188,
           0

'我 是 你 的'

In [2]:
torch.arange(1, 5)

tensor([1, 2, 3, 4])

In [4]:
torch.arange(1, 5).repeat(4, 2)

tensor([[1, 2, 3, 4, 1, 2, 3, 4],
        [1, 2, 3, 4, 1, 2, 3, 4],
        [1, 2, 3, 4, 1, 2, 3, 4],
        [1, 2, 3, 4, 1, 2, 3, 4]])

In [4]:
import torch
torch.ones(1, 4, 6)

tensor([[[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]]])

In [5]:
torch.ones(2, 4, 6) + torch.ones(1, 4, 6)

tensor([[[2., 2., 2., 2., 2., 2.],
         [2., 2., 2., 2., 2., 2.],
         [2., 2., 2., 2., 2., 2.],
         [2., 2., 2., 2., 2., 2.]],

        [[2., 2., 2., 2., 2., 2.],
         [2., 2., 2., 2., 2., 2.],
         [2., 2., 2., 2., 2., 2.],
         [2., 2., 2., 2., 2., 2.]]])